### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by bichikim** [DalYoon/nuber-server#1]
:) !
뭔가 저가 하는거랑 비슷한걸 하시고 계시네요 
graphql + jwt! 

혹시 맥주 좋아 하시나요?

**Comment by DalYoon** [comment]
안녕하세요! ㅎㅎ
graphql 요래저래 시도해 보고 있습니다 :D
맥주 물론 좋아합니다!

**Comment by bichikim** [comment]
꿀팁 같이 공유하면 좋겠네요

**Comment by DalYoon** [comment]
ㅎㅎ 냅 잘 못하지만
많이 공유하고 많이 배우고 싶습니다-

**Comment by bichikim** [comment]
넹
